import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const migrationPath = 'migrations/036_fix_board_reorder_text_ids.sql'

describe('board reorder database contract', () => {
  it('accepts the text board IDs generated by the upload API', () => {
    const uploadRoute = readFileSync('app/api/boards/route.ts', 'utf8')
    const migration = readFileSync(migrationPath, 'utf8')

    expect(uploadRoute).toContain('const boardId = `board-${ts}-${rand}`')
    expect(migration).toContain('p_ids text[]')
    expect(migration).toContain('drop function if exists public.reorder_room_boards(uuid, uuid[])')
    expect(migration).toContain('grant execute on function public.reorder_room_boards(uuid, text[]) to service_role')
  })
})
