-- Migration 040: what a crit concluded, and what you have to go and do.
--
-- Two tables with deliberately different shapes:
--
--   canvas_summaries    — ONE row per canvas, replaced each time you summarise.
--                         A summary is a current best description of the crit,
--                         not a log; keeping every past attempt would mean a UI
--                         that has to explain which one is "the" summary.
--
--   canvas_deliverables — MANY rows, each independently editable and tickable.
--                         These outlive the summary that produced them: you
--                         re-summarise, you keep your checkmarks.
--
--
-- WHY DELIVERABLES ARE NOT JUST TEXT IN THE SUMMARY
--
-- Because you act on them. A bulleted list inside a paragraph cannot be ticked
-- off, cannot survive a re-summarise, and cannot be listed across crits later.
-- The whole reason to extract them is that they become things with state.
--
--
-- WHY due_text IS TEXT AND NOT A DATE
--
-- The source is speech. People say "before next Tuesday", "for the final
-- review", "whenever you get the model printed" — and a DATE column forces
-- every one of those into either a wrong precise date or a NULL. Both lose what
-- was actually said. Stored as written; a real date column can be added
-- alongside it later if anything ever needs to sort or remind on one.
--
--
-- NO POLICIES, NO PUBLICATION
--
-- Same reasoning as 039: nothing subscribes to either table. These are read and
-- written by the one person whose crit it is, through the API, behind
-- resolveCanvasAccess. RLS on with zero policies means service-role only.
--
-- Idempotent: IF NOT EXISTS throughout.

BEGIN;

-- ---------------------------------------------------------------------------
-- canvas_summaries — the current summary of one crit.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS canvas_summaries (
  -- The canvas IS the key. A plain id plus a UNIQUE would say the same thing
  -- with an extra column and an extra index; making canvas_id the primary key
  -- states the one-per-canvas rule in the shape of the table.
  canvas_id    UUID PRIMARY KEY REFERENCES canvases(id) ON DELETE CASCADE,
  text         TEXT NOT NULL,
  -- How this summary was produced: pasted back from Claude by hand, or
  -- generated by a provider the app called itself. Recorded because a summary
  -- is a claim about a conversation, and how it was made is part of reading it.
  source       TEXT NOT NULL DEFAULT 'manual',
  -- updated_by, NOT created_by. The row is replaced by an upsert on every
  -- save, so whatever this column holds is the LAST writer — naming it
  -- created_by would have made it quietly false the second time anyone
  -- re-summarised. (Deliverables keep created_by, which stays true: those rows
  -- are inserted once and never upserted.)
  updated_by   TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT canvas_summaries_text_len_chk CHECK (char_length(text) <= 20000),
  CONSTRAINT canvas_summaries_text_present_chk CHECK (char_length(btrim(text)) > 0)
);

-- ---------------------------------------------------------------------------
-- canvas_deliverables — one thing to do.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS canvas_deliverables (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  canvas_id    UUID NOT NULL REFERENCES canvases(id) ON DELETE CASCADE,
  title        TEXT NOT NULL,
  detail       TEXT,
  due_text     TEXT,                              -- as spoken; see the header
  done         BOOLEAN NOT NULL DEFAULT false,
  -- Explicit ordering, so extraction order is preserved and a later drag-to-
  -- reorder has somewhere to write. Ties are expected and broken on
  -- (created_at, id) by the reader, the same total order the canvas nodes use.
  position     INTEGER NOT NULL DEFAULT 0,
  created_by   TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT canvas_deliverables_title_len_chk CHECK (char_length(title) <= 500),
  CONSTRAINT canvas_deliverables_title_present_chk CHECK (char_length(btrim(title)) > 0),
  CONSTRAINT canvas_deliverables_detail_len_chk CHECK (detail IS NULL OR char_length(detail) <= 4000),
  CONSTRAINT canvas_deliverables_due_len_chk CHECK (due_text IS NULL OR char_length(due_text) <= 200),
  -- INTEGER column: bounded so a client bug is a 400 rather than a 22003 that
  -- surfaces as a 500. Same reasoning as canvas_nodes.z.
  CONSTRAINT canvas_deliverables_position_chk CHECK (abs(position) <= 1000000)
);

CREATE INDEX IF NOT EXISTS canvas_deliverables_canvas_order_idx
  ON canvas_deliverables(canvas_id, position, created_at);

ALTER TABLE canvas_summaries    ENABLE ROW LEVEL SECURITY;  -- no policies: service-role only
ALTER TABLE canvas_deliverables ENABLE ROW LEVEL SECURITY;  -- no policies: service-role only

-- updated_at maintenance. update_updated_at_column() already exists (migration 014).
DROP TRIGGER IF EXISTS canvas_summaries_updated_at ON canvas_summaries;
CREATE TRIGGER canvas_summaries_updated_at
  BEFORE UPDATE ON canvas_summaries
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS canvas_deliverables_updated_at ON canvas_deliverables;
CREATE TRIGGER canvas_deliverables_updated_at
  BEFORE UPDATE ON canvas_deliverables
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMIT;
